project:
  type: website

website:
  favicon: customlogo_resize.png
  title: "MS"
  page-footer: "This site's content is licensed under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1' target='_blank' rel='license noopener noreferrer' style='display:inline-block;'>CC BY-NC-SA 4.0<img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1'><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1'><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1'><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1'></a>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Proposals
        menu:
          - text: Overview
            href: proposal.qmd
          - text: Proposal Document Structure
            href: proposalformat.qmd
          - text: Checklist
            href: proposalchecklist.qmd
    right:
      - text: Acknowledgements
        menu:
        - href: acknowledgement.qmd
          text: Territorial
        - href: citing.qmd
          text: License/Citing
      - icon: github
        menu:
          - text: webpage code
            url:  https://github.com/mateenshaikh/onlineresources5
          - text: mygithub
            url: https://github.com/mateenshaikh

format:
  html:
    theme:
      light: yeti
      dark: superhero
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true


editor: visual

