---
title: "Proposal checklist"
format:
  html: default
  pdf: default
  docx: default
format-links: [html,pdf,docx]
---

```{r, echo=FALSE}
checkboxsymbol=ifelse (knitr::is_html_output(),
"\\CheckBox",
"<input type='checkbox'>")
```

# SMART

-   [ ] Specific and Reproducible
-   [ ] Measurable
-   [ ] Achievable
-   [ ] Relevant
-   [ ] Timeline

# Writing Quality

-   [ ] Grammatically correct
-   [ ] Sentences flow from one to the next
-   [ ] Each paragraph has an appropriate topic and concluding sentence
-   [ ] Sections are clearly laid out and content within sections remain relevant to that section

# Style

-   [ ] Equations typeset, quantities explained
-   [ ] In-text content appropriately type-set
-   [ ] Figures/tables referenced in text and appropriately captioned
-   [ ] Appropriate use of sections, subsections, etc., and content respects corresponding structure

# References

-   [ ] Equations and in-text citations formatted and used appropriately
-   [ ] bibliography formatted correctly and consistently

# Formatting

-   [ ] Written in LaTeX (if appropriate).
-   [ ] 5--10 pages

# Introduction

-   [ ] Begins with an appropriate overview and introduces the purpose of project
-   [ ] Introduces major concepts with the data
-   [ ] Introduces major concepts of methodology

# Lit review

-   [ ] All relevant methods explained only in this section
-   [ ] Appropriate level of math explained
-   [ ] Describes algorithmic details
-   [ ] Avoids implementation details

# Methodology

-   [ ] Clearly outlines all steps in the proposal
-   [ ] Has plans for appropriate contingencies in analysis 
-   [ ] Likely that two other students could read the document, follow it, and come up with the same results in a month.
-   [ ] Any required resources are outlined (e.g., access to certain data, computing, etc.)


# Timeline

-   [ ] At least 4 appropriate checkpoints
-   [ ] Timeline leaves at least 1 month per draft


# Undesirable considerations

-   [ ] Statement acknowledging ending supervisory relationship for unacceptable progress
-   [ ] Statement acknowledging ending supervisory relationship for  suspected integrity violation such as plagiarism
-   [ ] Statement acknowledging that poor quality work/writing will be returned, delaying timelines

# Anticipated outcomes and appropriate authorship
-   [ ] For thesis, authorship, intended type of journal
-   [ ] For software, where it's disseminated



